GUI = false
Debug = false

[Env]
  UnitsPer = 1
  InputNames = ["B", "T", "S", "X", "V", "P", "E"]
  [Env.InputNameMap]
    B = 0
    E = 6
    P = 5
    S = 2
    T = 1
    V = 4
    X = 3

[Params]
  Sheet = ""
  Tag = ""
  Note = ""
  File = ""
  SaveAll = false
  Good = true

[Run]
  GPU = true
  NData = 16
  NThreads = 0
  Run = 0
  NRuns = 5
  NEpochs = 100
  NTrials = 196
  PCAInterval = 5
  TestInterval = -1

[Log]
  SaveWts = false
  Epoch = true
  Run = true
  Trial = false
  TestEpoch = false
  TestTrial = false
  NetData = false
