GUI = false
Debug = false

[Params]
  Sheet = ""
  Tag = ""
  Note = ""
  File = ""
  SaveAll = false
  Good = true
  [Params.Hidden1Size]
    X = 10
    Y = 10
  [Params.Hidden2Size]
    X = 10
    Y = 10

[Run]
  GPU = true
  NData = 16
  NThreads = 0
  Run = 0
  NRuns = 5
  NEpochs = 1000
  NZero = 2
  NTrials = 32
  TestInterval = 5
  PCAInterval = 5
  StartWts = ""

[Log]
  SaveWts = false
  Epoch = true
  Run = true
  Trial = false
  TestEpoch = false
  TestTrial = false
  NetData = false
