Includes = []
GUI = false
Debug = false

[Env]
  UnitsPer = 4

  [Env.Env]
    PctBlank = 0

[Params]
  Hid2 = false
  Sheet = ''
  Tag = ''
  Note = ''
  File = ''
  SaveAll = false
  Good = true

[Run]
  GPU = true
  NData = 16
  NThreads = 0
  Run = 0
  NRuns = 5
  NEpochs = 100
  NTrials = 196
  PCAInterval = 5
  TestInterval = -1

[Log]
  SaveWts = false
  Epoch = true
  Run = true
  Trial = false
  TestEpoch = false
  TestTrial = false
  NetData = false
