[[Base]]
  Sel = ".InputLayer"
  Desc = ""
  [Base.Params]
    "Layer.Acts.Decay.Act" = "1.0"
    "Layer.Acts.Decay.Glong" = "1.0"

[[Base]]
  Sel = "#CS"
  Desc = "expect act"
  [Base.Params]
    "Layer.Inhib.ActAvg.Nominal" = "0.05"

[[Base]]
  Sel = "#ContextIn"
  Desc = "expect act"
  [Base.Params]
    "Layer.Inhib.ActAvg.Nominal" = "0.025"

[[Base]]
  Sel = ".VSPatchLayer"
  Desc = ""
  [Base.Params]
    "Layer.Inhib.Layer.Gi" = "0.5"
    "Layer.Inhib.Pool.Gi" = "0.5"
    "Layer.Learn.NeuroMod.AChLRateMod" = "0"
    "Layer.Learn.NeuroMod.DipGain" = "1"
    "Layer.Learn.RLRate.SigmoidMin" = "0.05"
    "Layer.Learn.TrgAvgAct.GiBaseInit" = "0"

[[Base]]
  Sel = ".VTALayer"
  Desc = ""
  [Base.Params]
    "Layer.VTA.AChThr" = "0.5"
    "Layer.VTA.CeMGain" = "0.5"
    "Layer.VTA.LHbGain" = "1.25"

[[Base]]
  Sel = ".MatrixLayer"
  Desc = "all mtx"
  [Base.Params]
    "Layer.Acts.Kir.Gbar" = "2"
    "Layer.Learn.RLRate.Diff" = "false"
    "Layer.Learn.RLRate.On" = "true"

[[Base]]
  Sel = "#BLAposExtD2"
  Desc = ""
  [Base.Params]
    "Layer.Inhib.Layer.Gi" = "1.8"
    "Layer.Inhib.Pool.Gi" = "1.0"
    "Layer.Learn.NeuroMod.DAModGain" = "0"

[[Base]]
  Sel = ".PTMaintLayer"
  Desc = "time integration params"
  [Base.Params]
    "Layer.Acts.Dend.ModGain" = "1.5"

[[Base]]
  Sel = "#OFCposPT"
  Desc = ""
  [Base.Params]
    "Layer.Acts.SMaint.Gbar" = "0.4"

[[Base]]
  Sel = ".PTPredLayer"
  Desc = ""
  [Base.Params]
    "Layer.CT.GeGain" = "0.1"

[[Base]]
  Sel = ".LDTLayer"
  Desc = ""
  [Base.Params]
    "Layer.LDT.MaintInhib" = "0.8"

[[Base]]
  Sel = "#OFCposPTp"
  Desc = ""
  [Base.Params]
    "Layer.Inhib.ActAvg.Nominal" = "0.025"
    "Layer.Inhib.Pool.Gi" = "1"

[[Base]]
  Sel = "#SC"
  Desc = ""
  [Base.Params]
    "Layer.Acts.KNa.Slow.Max" = "0.5"

[[Base]]
  Sel = "#CostP"
  Desc = ""
  [Base.Params]
    "Layer.Pulvinar.DriveScale" = "0.2"

[[Base]]
  Sel = ".VSMatrixPath"
  Desc = ""
  [Base.Params]
    "Path.Learn.Trace.LearnThr" = "0.1"

[[Base]]
  Sel = ".SuperToThal"
  Desc = ""
  [Base.Params]
    "Path.PathScale.Abs" = "4.0"

[[Base]]
  Sel = ".BLAExtPath"
  Desc = ""
  [Base.Params]
    "Path.BLA.NegDeltaLRate" = "1"
    "Path.Learn.LRate.Base" = "0.05"
    "Path.PathScale.Abs" = "4"

[[Base]]
  Sel = ".GPiToBGThal"
  Desc = "inhibition from GPi to MD"
  [Base.Params]
    "Path.PathScale.Abs" = "3"

[[Base]]
  Sel = ".PTpToBLAExt"
  Desc = "modulatory so only active with -da, drives extinction learning based on maintained goal rep"
  [Base.Params]
    "Path.PathScale.Abs" = "1"

[[Base]]
  Sel = "#BLAposAcqD1ToOFCpos"
  Desc = "strong, high variance"
  [Base.Params]
    "Path.PathScale.Abs" = "2"

[[Base]]
  Sel = ".CSToBLApos"
  Desc = ""
  [Base.Params]
    "Path.Learn.LRate.Base" = "0.05"

[[Base]]
  Sel = ".BLAAcqToGo"
  Desc = ""
  [Base.Params]
    "Path.PathScale.Abs" = "4"

[[Base]]
  Sel = ".BLAExtToAcq"
  Desc = "fixed inhibitory"
  [Base.Params]
    "Path.PathScale.Abs" = "1.0"

[[Base]]
  Sel = ".VSPatchPath"
  Desc = ""
  [Base.Params]
    "Path.Learn.LRate.Base" = "0.02"
    "Path.Learn.Trace.LearnThr" = "0"
    "Path.PathScale.Abs" = "3"
