Includes = [
  '30notes.toml'
]
GUI = false
Debug = false

[Env]
  UnitsPer = 4
  FullSong = false
  PlayTarg = false
  TestClamp = true

[Params]
  Hid2 = false
  Sheet = ''
  Tag = ''
  Note = ''
  File = ''
  SaveAll = false
  Good = true

[Run]
  GPU = true
  NData = 4
  NThreads = 0
  Run = 0
  NRuns = 5
  NEpochs = 100
  NTrials = 128
  PCAInterval = 5
  TestInterval = -1

[Log]
  SaveWts = false
  Epoch = true
  Run = true
  Trial = false
  TestEpoch = false
  TestTrial = false
  NetData = false
