[[Base]]
  Sel = "Layer"
  Desc = "generic params for all layers"
  [Base.Params]
    "Layer.Acts.Clamp.Ge" = "1.5"

[[Base]]
  Sel = ".PFCLayer"
  Desc = "pfc layers: slower trgavgact"
  [Base.Params]
    "Layer.Learn.TrgAvgAct.SynScaleRate" = "0.0002"

[[Base]]
  Sel = ".PTMaintLayer"
  Desc = "time integration params"
  [Base.Params]
    "Layer.Acts.Dend.ModGain" = "1.5"
    "Layer.Learn.NeuroMod.AChDisInhib" = "0.0"

[[Base]]
  Sel = ".VSTNLayer"
  Desc = "all VSTN"
  [Base.Params]
    "Layer.Acts.Init.GeBase" = "0.1"
    "Layer.Acts.Kir.Gbar" = "10"
    "Layer.Acts.SKCa.CaRDecayTau" = "80"
    "Layer.Acts.SKCa.Gbar" = "2"
    "Layer.Learn.NeuroMod.AChDisInhib" = "0"

[[Base]]
  Sel = ".PTPredLayer"
  Desc = ""
  [Base.Params]
    "Layer.CT.DecayTau" = "50"
    "Layer.CT.GeGain" = "0.05"
    "Layer.Inhib.ActAvg.Nominal" = "0.1"
    "Layer.Learn.NeuroMod.AChDisInhib" = "0"

[[Base]]
  Sel = ".CS"
  Desc = "need to adjust Nominal for number of CSs -- now down automatically"
  [Base.Params]
    "Layer.Inhib.ActAvg.Nominal" = "0.1"

[[Base]]
  Sel = "#OFCposPTp"
  Desc = ""
  [Base.Params]
    "Layer.Inhib.ActAvg.Nominal" = "0.1"
    "Layer.Inhib.Pool.Gi" = "1.4"

[[Base]]
  Sel = "#ILposPTp"
  Desc = ""
  [Base.Params]
    "Layer.Inhib.Layer.Gi" = "1.2"

[[Base]]
  Sel = "#ILnegPTp"
  Desc = ""
  [Base.Params]
    "Layer.Inhib.Layer.Gi" = "1.2"

[[Base]]
  Sel = "#OFCneg"
  Desc = ""
  [Base.Params]
    "Layer.Inhib.ActAvg.Nominal" = "0.1"

[[Base]]
  Sel = ".VSMatrixLayer"
  Desc = "vs mtx"
  [Base.Params]
    "Layer.Acts.Dend.ModGain" = "1"
    "Layer.Acts.Kir.Gbar" = "2"
    "Layer.Inhib.Layer.On" = "false"
    "Layer.Inhib.Pool.FB" = "0"
    "Layer.Inhib.Pool.Gi" = "0.5"
    "Layer.Learn.NeuroMod.BurstGain" = "1"
    "Layer.Learn.NeuroMod.DAModGain" = "0"
    "Layer.Learn.RLRate.SigmoidMin" = "0.001"

[[Base]]
  Sel = "#BLAposAcqD1"
  Desc = ""
  [Base.Params]
    "Layer.Inhib.Layer.Gi" = "2"
    "Layer.Inhib.Pool.Gi" = "1"

[[Base]]
  Sel = "#BLAposExtD2"
  Desc = ""
  [Base.Params]
    "Layer.CT.GeGain" = "0.5"

[[Base]]
  Sel = "#BLAnegAcqD2"
  Desc = ""
  [Base.Params]
    "Layer.Inhib.Layer.Gi" = "1.2"

[[Base]]
  Sel = ".VSPatchLayer"
  Desc = ""
  [Base.Params]
    "Layer.Inhib.Pool.FB" = "0"
    "Layer.Inhib.Pool.Gi" = "0.5"
    "Layer.Learn.NeuroMod.BurstGain" = "1"
    "Layer.Learn.NeuroMod.DipGain" = "1"
    "Layer.Learn.RLRate.SigmoidMin" = "0.01"
    "Layer.Learn.TrgAvgAct.GiBaseInit" = "0"

[[Base]]
  Sel = ".LDTLayer"
  Desc = ""
  [Base.Params]
    "Layer.LDT.MaintInhib" = "2.0"

[[Base]]
  Sel = "#SC"
  Desc = ""
  [Base.Params]
    "Layer.Acts.KNa.Slow.Max" = "0.8"

[[Base]]
  Sel = ".PFCPath"
  Desc = "pfc path params -- more robust to long-term training"
  [Base.Params]
    "Path.Learn.LRate.Base" = "0.01"
    "Path.Learn.Trace.SubMean" = "1"

[[Base]]
  Sel = ".PTtoPred"
  Desc = "stronger drive on pt pred"
  [Base.Params]
    "Path.PathScale.Abs" = "1"

[[Base]]
  Sel = "#BLAposAcqD1ToOFCpos"
  Desc = "stronger"
  [Base.Params]
    "Path.PathScale.Abs" = "1.5"

[[Base]]
  Sel = "#OFCposToILpos"
  Desc = "stronger"
  [Base.Params]
    "Path.PathScale.Abs" = "3"

[[Base]]
  Sel = ".USToBLAExtInhib"
  Desc = ""
  [Base.Params]
    "Path.PathScale.Abs" = "2"

[[Base]]
  Sel = "#ILposToPLutil"
  Desc = "not good to make this stronger"
  [Base.Params]
    "Path.PathScale.Abs" = "1"

[[Base]]
  Sel = ".MToACC"
  Desc = ""
  [Base.Params]
    "Path.PathScale.Abs" = "3"

[[Base]]
  Sel = ".VSMatrixPath"
  Desc = ""
  [Base.Params]
    "Path.Learn.LRate.Base" = "0.02"
    "Path.Learn.Trace.LearnThr" = "0.1"
    "Path.PathScale.Abs" = "1.5"

[[Base]]
  Sel = ".ToSC"
  Desc = ""
  [Base.Params]
    "Path.PathScale.Abs" = "2"

[[Base]]
  Sel = ".DrivesToMtx"
  Desc = ""
  [Base.Params]
    "Path.PathScale.Abs" = "1"

[[Base]]
  Sel = ".BLAExtPath"
  Desc = "ext learns relatively fast"
  [Base.Params]
    "Path.Learn.LRate.Base" = "0.05"

[[Base]]
  Sel = ".BLAAcqToGo"
  Desc = "must dominate"
  [Base.Params]
    "Path.PathScale.Abs" = "4"
    "Path.PathScale.Rel" = "1"

[[Base]]
  Sel = ".BLAExtToAcq"
  Desc = ""
  [Base.Params]
    "Path.PathScale.Abs" = "1.0"

[[Base]]
  Sel = ".CSToBLApos"
  Desc = ""
  [Base.Params]
    "Path.Learn.LRate.Base" = "0.01"

[[Base]]
  Sel = ".PFCToVSMtx"
  Desc = "contextual, should be weaker"
  [Base.Params]
    "Path.PathScale.Abs" = "1"
    "Path.PathScale.Rel" = "0.1"

[[Base]]
  Sel = "#OFCposToVMtxGo"
  Desc = "specific best go signal"
  [Base.Params]
    "Path.PathScale.Abs" = "3"

[[Base]]
  Sel = "#ILposToVMtxGo"
  Desc = "specific best go signal"
  [Base.Params]
    "Path.PathScale.Abs" = "3"

[[Base]]
  Sel = "#ACCcostToVMtxGo"
  Desc = "costs.."
  [Base.Params]
    "Path.PathScale.Abs" = "3"

[[Base]]
  Sel = ".VSPatchPath"
  Desc = ""
  [Base.Params]
    "Path.Learn.LRate.Base" = "0.02"
    "Path.Learn.Trace.LearnThr" = "0"
    "Path.PathScale.Abs" = "4"

[[Base]]
  Sel = ".CSToBLANovelInhib"
  Desc = ""
  [Base.Params]
    "Path.Learn.LRate.Base" = "0.005"

[[Base]]
  Sel = ".SuperToThal"
  Desc = ""
  [Base.Params]
    "Path.PathScale.Abs" = "4"

[[Base]]
  Sel = ".SuperToPT"
  Desc = ""
  [Base.Params]
    "Path.PathScale.Abs" = "0.5"

[[Base]]
  Sel = ".GPiToBGThal"
  Desc = "inhibition from GPi to MD"
  [Base.Params]
    "Path.PathScale.Abs" = "5"

[[Base]]
  Sel = ".BLAFromNovel"
  Desc = "Note: this setting is overwritten in boa.go ApplyParams"
  [Base.Params]
    "Path.PathScale.Abs" = "3"
    "Path.PathScale.Rel" = "0.1"
