GUI = false
Debug = false

[Env]
  NOutPer = 5

[Params]
  Sheet = ""
  Tag = ""
  Note = ""
  File = ""
  SaveAll = false
  Good = true
  [Params.V1V4Prjn]
    Recip = false
    Wrap = true
    [Params.V1V4Prjn.Size]
      X = 4
      Y = 4
    [Params.V1V4Prjn.Skip]
      X = 2
      Y = 2
    [Params.V1V4Prjn.Start]
      X = -1
      Y = -1
    [Params.V1V4Prjn.GaussFull]
      On = true
      Sigma = 0.6
      Wrap = true
      CtrMove = 0.8
    [Params.V1V4Prjn.GaussInPool]
      On = true
      Sigma = 0.6
      Wrap = true
      CtrMove = 0.8
    [Params.V1V4Prjn.SigFull]
      On = false
      Gain = 0.05
      CtrMove = 0.5
    [Params.V1V4Prjn.SigInPool]
      On = false
      Gain = 0.05
      CtrMove = 0.5
    [Params.V1V4Prjn.TopoRange]
      Min = 0.8
      Max = 1.0

[Run]
  GPU = true
  NData = 16
  NThreads = 0
  Run = 0
  NRuns = 1
  NEpochs = 200
  NTrials = 128
  PCAInterval = 5
  TestInterval = -1

[Log]
  SaveWts = false
  Epoch = true
  Run = true
  Trial = false
  TestEpoch = false
  TestTrial = false
  NetData = false
